#!/bin/bash

if [[ -z $SHEET_FILE ]]; then
    SHEET_FILE=~/.ti
fi

if [[ -z $SHEET_CURRENT_FILE ]]; then
    SHEET_CURRENT_FILE="$SHEET_FILE-current"
fi

action-on () {
    if [[ -f $SHEET_CURRENT_FILE ]]; then
        echo 'A task is already active. Please off it first.' >&2
        return 1
    fi
    project_name="$1"
    if [[ -z $project_name ]]; then
        echo 'No projct name given. Doing nothing.' >&2
        return 1
    fi
    shift
    start_time="$(read-time "$@")"
    echo "$project_name [$start_time]" >> $SHEET_CURRENT_FILE
}

action-off () {
    ensure-working!
    stop_time="$(read-time "$@")"
    echo >> $SHEET_FILE
    project="$(head -1 $SHEET_CURRENT_FILE | sed 's/ \[.\+$//')"
    head -1 $SHEET_CURRENT_FILE | sed "s^$^ to [$stop_time]^" >> $SHEET_FILE
    cat $SHEET_CURRENT_FILE | awk 'NR != 1' >> $SHEET_FILE
    echo "So you stopped working on $project."
    rm $SHEET_CURRENT_FILE
}

action-note () {
    ensure-working!
    desc="$*"
    if [[ -z $desc && -z $_NON_INTERACTIVE ]]; then
        "$EDITOR" "$SHEET_CURRENT_FILE"
    elif [[ ! -z $desc ]]; then
        echo "  $desc" >> $SHEET_CURRENT_FILE
    fi
}

action-status () {
    ensure-working!
    pline="$(head -1 $SHEET_CURRENT_FILE)"
    project="$(echo $pline | sed 's/ \[.\+$//')"
    from_time="$(echo $pline | sed 's/^.\+\[//' | sed 's/\]$//')"
    if hash dtime 2>&-; then
        echo "You have been working on '$project' for $(dtime "$from_time")."
    else
        echo "You are working on '$project' since $from_time."
    fi
}

action-edit () {
    "$EDITOR" "$SHEET_FILE"
}

read-time () {
    when="$@"
    if [[ -z $when ]]; then
        when=now
    fi
    date --date="$when"
}

is-working? () {
    [[ -f $SHEET_CURRENT_FILE ]]
    return $?
}

ensure-working! () {
    if ! is-working?; then
        echo "For all I know, you aren't working on anything. I don't know what to do." >&2
        echo "Use $0 on <project-name> [description]" >&2
        exit 1
    fi
}

list-actions () {
    compgen -A function action- | sed 's/^action-//'
}

main () {
    matching_actions="$(list-actions | grep "^$1")"
    match_count="$(echo "$matching_actions" | wc -l)"
    if [[ $match_count == 0 ]]; then
        echo "No action '$1' found" >&2
    elif [[ $match_count == 1 ]]; then
        shift
        "action-$matching_actions" "$@"
        return $?
    else
        echo "Ambiguous action name:" >&2
        echo "$matching_actions" | sed 's/^/  /' >&2
    fi
    return 1
}

main "$@"
